title: Carpenter too Software Engineer: A blog about one journey.
author: Eric Barrett
email: ebarrett576@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  Follow me as I traverse out of the construction industry and deep into the software engineering and development side of life.
  This blog will keep those informed of my studies, some of my past solo projects and the projects i contribute to.

# social links
twitter_username: N/A
github_username:  theloneshepherd

theme: minima


show_excerpts: true # set to false to remove excerpts on the homepage
